### ISSUE TITLE
Help: Can't start Riders with this enabled

### ISSUE THREAD

**Issue by LunarmanEXE** [Sewer56/Riders.Controller.Hook#2]
[2024-01-16 23.25.17 ~ SonicRiders.txt](https://github.com/Sewer56/Riders.Controller.Hook/files/13956886/2024-01-16.23.25.17.SonicRiders.txt)
I've tried every suggestion I could find, restarted my PC at least 5 times and the game still crashes before startup. I still get the same exact messages in every log including the one attached above. I get the error in the image below every single time.
![another error](https://github.com/Sewer56/Riders.Controller.Hook/assets/54486179/6b804e5c-6d6a-4ed5-a11b-80478082d610)
I Just don't know what to do.

**Comment by Sewer56** [comment]
Your game might have an EXE file with copy protection (SafeDisc), or a custom repack (e.g. some Russian releases).

Mods target a cracked US version of the game (which SEGA also re-released officially in the 'Sonic PC Collection'). The Reloaded launcher should have warned you while adding the game, but you probably ignored the message.

**Comment by LunarmanEXE** [comment]
> Your game might have an EXE file with copy protection (SafeDisc), or a custom repack (e.g. some Russian releases).
> 
> Mods target a cracked US version of the game (which SEGA also re-released officially in the 'Sonic PC Collection'). The Reloaded launcher should have warned you while adding the game, but you probably ignored the message.

I know for a fact that the Reloaded launcher didn't warn me or anything while adding the game. I don't ignore things like that when they happen.

Edit: Turns out I just had a bad copy of the game, but the launcher still didn't say anything about it.
